name: Caller

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: devops-max/CICD_Java_gradle_application/.github/workflows/reusable.yml@main
    with:
      runs-on: self-hosted
