name: Java CI with Gradle

on:
  pull_request:
    branches: [ main ]
env:
  DATREE_TOKEN: ${{secrets.DATREE_TOKEN}}
  
jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Install Datree
      run: curl https://get.datree.io | /bin/bash
    - name: Run Datree's policy check
      run: datree test kube.yaml
